### ISSUE TITLE
Cannot redefine property: tap

### ISSUE THREAD

**Issue by dillingham** [debute/laravel-mix-blade-reload#1]
Fresh install of Laravel 8 with Laravel mix: 6.0.6

```
webpack-cli] TypeError: Cannot redefine property: tap
    at Function.defineProperty (<anonymous>)
    at Object.<anonymous> (node_modules/laravel-mix-blade-reload/node_modules/laravel-mix/src/helpers.js:21:8)
```

```js
const mix = require('laravel-mix');

require('laravel-mix-blade-reload');

mix.js('resources/js/app.js', 'public/js')
    .bladeReload()
    .postCss('resources/css/app.css', 'public/css', [
        //
    ]);

```

My **guess** is maybe releasing a 2.0 with laravel-mix 6.0 instead of 5.0 as a dependency

**Comment by krehak** [comment]
Hi,

thanks for the report. I'm sorry for the late response but I'm pretty lazy these last days :) I'm about to look at it and fix it.

**Comment by krehak** [comment]
I'm very sorry, but I can't help you. Changing the laravel-mix version from 5 to 6 is not enough, because for unknown reasons webpack's devServer.after is not working anymore and I'm unable to find a solution. I suggest you not to use this plugin for laravel-mix version 6+, use [this browserSync solution](https://laravel.com/docs/8.x/mix#browsersync-reloading) instead. At least until I have enough time to keep updating these plugins, since I'm not using them at all (pure webpack, gulp, or parcel.js are better options for me).

**Comment by dillingham** [comment]
@krehak haha I totally understand. I appreciate you looking into it and linking me to an alternative. I completely overlooked that option. Thanks!

**Comment by krehak** [comment]
@dillingham I overlooked the option as well, I just found it by accident :) Glad I helped you with the alternative.

**Comment by krehak** [comment]
@dillingham I almost forget :) Anyway, I finally found a way to support laravel-mix 6, so now you can use `laravel-mix-blade-reload` version 2 - 2a5c1985fe71f4201d3c82abdc58a8b51e4efc8d

**Comment by dillingham** [comment]
@krehak thats awesome 🎉 Definitely will give it a spin as soon as Im working with blade again.

thanks for doing that :)

**Comment by krehak** [comment]
@dillingham you are welcome :)
